<?php

namespace Database\Seeders\Countries;

use App\Models\Countries\Country;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CountriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        foreach($this->countries() as $country)
        {
            Country::create(['name'=>$country]);
        }
    }
    private function countries(): array
    {
        return[
            'Afghanistan',
            'Albania',
            'Algeria',
            'Andorra',
            'Angola',
            'Antigua and Barbuda',
            'Argentina',
            'Armenia',
            'Australia',
            'Azerbaijan',
            'Bahamas',
            'Bahrain',
            'Bangladesh',
            'Barbados',
            'Belgium',
            'Belize',
            'Benin',
            'Bhutan',
            'Bolivia',
            'Bosnia and Herzegovina',
            'Botswana',
            'Brazil',
            'Brunei',
            'Bulgaria',
            'Burkina Faso',
            'Burundi',
            'Chile',
            'Colombia',
            'Comoros',
            'Costa Rica',
            'Democratic Republic of the Congo',
            'Denmark',
            'Djibouti',
            'Dominica',
            'Dominican Republic',
            'Germany',
            'Ecuador',
            'Egypt',
            'Equatorial Guinea',
            'El Salvador',
            'Eritrea',
            'Estonia',
            'Ethiopia',
            'Fiji',
            'Philippines',
            'Finland',
            'France',
            'Gabon',
            'Gambia',
            'Georgia',
            'Ghana',
            'Grenada',
            'Greece',
            'Guatemala',
            'Guinea',
            'Guinea-Bissau',
            'Guyana',
            'Haiti',
            'Honduras',
            'Hungary',
            'Ireland',
            'India',
            'Indonesia',
            'Iran',
            'Iraq',
            'Israel',
            'Italy',
            'Côte d’Ivoire',
            'Jamaica',
            'Japan',
            'Yemen',
            'Jordan',
            'Cape Verde Islands',
            'Cambodia',
            'Cameroon',
            'Canada',
            'Kazakhstan',
            'Qatar',
            'Kenya',
            'Kyrgyzstan',
            'Kiribati',
            'Kuwait',
            'Croatia',
            'Cuba',
            'Laos',
            'Latvia',
            'Lesotho',
            'Lebanon',
            'Liberia',
            'Libya',
            'Liechtenstein',
            'Lithuania',
            'Luxembourg',
            'Madagascar',
            'Malawi',
            'Malaysia',
            'Maldives',
            'Mali',
            'Malta',
            'Morocco',
            'Marshall Islands',
            'Mauritania',
            'Mauritius',
            'Mexico',
            'Myanmar (Burma)',
            'Micronesia',
            'Moldova',
            'Monaco',
            'Mongolia',
            'Montenegro',
            'Mozambique',
            'Namibia',
            'Nauru',
            'Nepal',
            'Netherlands',
            'New Zealand',
            'Nicaragua',
            'Niger',
            'Nigeria',
            'North Korea',
            'Norway',
            'Ukraine',
            'Uzbekistan',
            'Oman',
            'Austria',
            'East Timor',
            'Pakistan',
            'Palau',
            'Panama',
            'Papua New Guinea',
            'Paraguay',
            'Peru',
            'Pole/Poland',
            'Portugal',
            'Republic of the Congo',
            'Macedonia',
            'Romania',
            'Russia',
            'Rwanda',
            'Samoa',
            'San Marino',
            'Saudi Arabia',
            'São Tomé and Principe',
            'Senegal',
            'Central African Republic',
            'Serbia',
            'Seychelles',
            'China',
            'Sierra Leone',
            'Singapore',
            'Cyprus',
            'Syria',
            'Slovakia',
            'Slovenia',
            'Sudan',
            'Solomon Islands',
            'Somalia',
            'Spain',
            'Sri Lanka',
            'Saint Kitts and Nevis',
            'St. Lucia',
            'St. Vincent and the Grenadines',
            'South Africa',
            'Suid-Korea/South Korea',
            'South Sudan',
            'Suriname',
            'Swaziland',
            'Sweden',
            'Switzerland',
            'Tajikistan',
            'Taiwan',
            'Tanzania',
            'Thailand',
            'Tonga',
            'Togo',
            'Trinidad and Tobago',
            'Chad',
            'Czech Republic',
            'Tunisia',
            'Turkmenistan',
            'Turkey',
            'Tuvalu',
            'Uganda',
            'Uruguay',
            'Vanuatu',
            'Venezuela',
            'United Arab Emirates',
            'United Kingdom',
            'United States of America',
            'Vietnam',
            'Belarus',
            'Iceland',
            'Zambia',
            'Zimbabwe'
        ];
    }
}
