<?php

namespace Database\Seeders\Acl;

use App\Enums\Acl\PermissionEnum;
use App\Models\Acl\Module;
use App\Models\Acl\Permission;
use Illuminate\Database\Seeder;

class PermissionsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $permissions = [
            'acl' => [
                [PermissionEnum::VIEW_ACL_INDEX->value],
                /*** Acl Modules */
                [PermissionEnum::VIEW_ANY_MODULES->value],
                [PermissionEnum::VIEW_MODULE->value],
                [PermissionEnum::CREATE_MODULE->value],
                [PermissionEnum::UPDATE_MODULE->value],
                [PermissionEnum::DELETE_MODULE->value],
                [PermissionEnum::RESTORE_MODULE->value],
                [PermissionEnum::FORCE_DELETE_MODULE->value],
                [PermissionEnum::IMPORT_MODULES->value],
                [PermissionEnum::EXPORT_MODULES->value],
                [PermissionEnum::VIEW_MODULES_AUDIT_TRAIL->value],
                /*** Acl Roles */
                [PermissionEnum::VIEW_ANY_ROLES->value],
                [PermissionEnum::VIEW_ROLE->value],
                [PermissionEnum::CREATE_ROLE->value],
                [PermissionEnum::UPDATE_ROLE->value],
                [PermissionEnum::DELETE_ROLE->value],
                [PermissionEnum::RESTORE_ROLE->value],
                [PermissionEnum::FORCE_DELETE_ROLE->value],
                [PermissionEnum::IMPORT_ROLES->value],
                [PermissionEnum::EXPORT_ROLES->value],
                [PermissionEnum::VIEW_ROLES_AUDIT_TRAIL->value],
                /*** Acl Permissions */
                [PermissionEnum::VIEW_ANY_PERMISSIONS->value],
                [PermissionEnum::VIEW_PERMISSION->value],
                [PermissionEnum::CREATE_PERMISSION->value],
                [PermissionEnum::UPDATE_PERMISSION->value],
                [PermissionEnum::DELETE_PERMISSION->value],
                [PermissionEnum::RESTORE_PERMISSION->value],
                [PermissionEnum::FORCE_DELETE_PERMISSION->value],
                [PermissionEnum::IMPORT_PERMISSIONS->value],
                [PermissionEnum::EXPORT_PERMISSIONS->value],
                [PermissionEnum::VIEW_PERMISSIONS_AUDIT_TRAIL->value],
            ],
            'communications' => [
                [PermissionEnum::VIEW_ANY_COMMUNICATIONS->value],
                [PermissionEnum::VIEW_COMMUNICATION->value],
                [PermissionEnum::CREATE_COMMUNICATION->value],
                [PermissionEnum::UPDATE_COMMUNICATION->value],
                [PermissionEnum::DELETE_COMMUNICATION->value],
                [PermissionEnum::RESTORE_COMMUNICATION->value],
                [PermissionEnum::FORCE_DELETE_COMMUNICATION->value],
                [PermissionEnum::IMPORT_COMMUNICATIONS->value],
                [PermissionEnum::EXPORT_COMMUNICATIONS->value],
                [PermissionEnum::CRUD_COMMUNICATION_SETTINGS->value],
                [PermissionEnum::VIEW_COMMUNICATION_AUDIT_TRAIL->value],
            ],
            'dashboards' => [
                [PermissionEnum::VIEW_ANY_DASHBOARD->value],
                [PermissionEnum::VIEW_DASHBOARD->value],
            ],
            'reports' => [
                [PermissionEnum::VIEW_ANY_REPORTS->value],
                [PermissionEnum::VIEW_REPORT->value],
                [PermissionEnum::CREATE_REPORT->value],
                [PermissionEnum::UPDATE_REPORT->value],
                [PermissionEnum::DELETE_REPORT->value],
                [PermissionEnum::RESTORE_REPORT->value],
                [PermissionEnum::FORCE_DELETE_REPORT->value],
                [PermissionEnum::IMPORT_REPORTS->value],
                [PermissionEnum::EXPORT_REPORTS->value],
            ],
            'tenants' => [
                [PermissionEnum::VIEW_ANY_TENANTS->value],
                [PermissionEnum::VIEW_TENANT->value],
                [PermissionEnum::CREATE_TENANT->value],
                [PermissionEnum::UPDATE_TENANT->value],
                [PermissionEnum::DELETE_TENANT->value],
                [PermissionEnum::RESTORE_TENANT->value],
                [PermissionEnum::FORCE_DELETE_TENANT->value],
                [PermissionEnum::IMPORT_TENANTS->value],
                [PermissionEnum::EXPORT_TENANTS->value],
                [PermissionEnum::CRUD_TENANTS_SETTINGS->value],
                [PermissionEnum::VIEW_TENANTS_AUDIT_TRAIL->value],
                [PermissionEnum::MANAGE_OWN_TENANT_DATA->value],
            ],
            'users' => [
                [PermissionEnum::VIEW_ANY_USERS->value],
                [PermissionEnum::VIEW_USERS->value],
                [PermissionEnum::CREATE_USERS->value],
                [PermissionEnum::UPDATE_USERS->value],
                [PermissionEnum::DELETE_USERS->value],
                [PermissionEnum::RESTORE_USERS->value],
                [PermissionEnum::FORCE_DELETE_USERS->value],
                [PermissionEnum::IMPORT_USERS->value],
                [PermissionEnum::EXPORT_USERS->value],
                [PermissionEnum::CRUD_USERS_SETTINGS->value],
                [PermissionEnum::VIEW_USERS_AUDIT_TRAIL->value],
            ],
            'root' => [
                [PermissionEnum::ROOT_MANAGE->value],
            ],
            'settings' => [
                [PermissionEnum::VIEW_SETTINGS->value],
                [PermissionEnum::CREATE_SETTINGS->value],
                [PermissionEnum::UPDATE_SETTINGS->value],
                [PermissionEnum::DELETE_SETTINGS->value],
                [PermissionEnum::RESTORE_SETTINGS->value],
                [PermissionEnum::FORCE_DELETE_SETTINGS->value],
                [PermissionEnum::IMPORT_SETTINGS->value],
                [PermissionEnum::EXPORT_SETTINGS->value],
                [PermissionEnum::VIEW_SETTINGS_AUDIT_TRAIL->value],
                [PermissionEnum::VIEW_INSTITUTION_SETTINGS->value],
                [PermissionEnum::VIEW_INSTITUTION_SETTINGS->value],
                [PermissionEnum::CREATE_INSTITUTION_SETTINGS->value],
                [PermissionEnum::UPDATE_INSTITUTION_SETTINGS->value],
                [PermissionEnum::DELETE_INSTITUTION_SETTINGS->value],
                [PermissionEnum::RESTORE_INSTITUTION_SETTINGS->value],
                [PermissionEnum::FORCE_DELETE_INSTITUTION_SETTINGS->value],
                [PermissionEnum::IMPORT_INSTITUTION_SETTINGS->value],
                [PermissionEnum::EXPORT_INSTITUTION_SETTINGS->value],
                [PermissionEnum::VIEW_INSTITUTION_SETTINGS_AUDIT_TRAIL->value],
            ],
            'institution' => [
                [PermissionEnum::VIEW_ANY_DEPARTMENT_METADATA->value],
                [PermissionEnum::VIEW_DEPARTMENT_METADATA->value],
                [PermissionEnum::CREATE_DEPARTMENT_METADATA->value],
                [PermissionEnum::UPDATE_DEPARTMENT_METADATA->value],
                [PermissionEnum::DELETE_DEPARTMENT_METADATA->value],
                [PermissionEnum::RESTORE_DEPARTMENT_METADATA->value],
                [PermissionEnum::FORCE_DELETE_DEPARTMENT_METADATA->value],
                [PermissionEnum::IMPORT_DEPARTMENT_METADATA->value],
                [PermissionEnum::EXPORT_DEPARTMENT_METADATA->value],
                [PermissionEnum::VIEW_DEPARTMENT_METADATA_AUDIT_TRAIL->value],
                [PermissionEnum::SETUP_DEPARTMENT_LEVELS->value],
                [PermissionEnum::SETUP_DEPARTMENT_COURSES->value],
                [PermissionEnum::SETUP_DEPARTMENT_CLASS_SIZES->value],
                [PermissionEnum::SETUP_DEPARTMENT_WORKFLOWS->value],
                [PermissionEnum::VIEW_ONLY_OWN_DEPARTMENT->value],
                [PermissionEnum::VIEW_ANY_DOCUMENT_TEMPLATES->value],
                [PermissionEnum::VIEW_DOCUMENT_TEMPLATES->value],
                [PermissionEnum::CREATE_DOCUMENT_TEMPLATES->value],
                [PermissionEnum::UPDATE_DOCUMENT_TEMPLATES->value],
                [PermissionEnum::DELETE_DOCUMENT_TEMPLATES->value],
                [PermissionEnum::RESTORE_DOCUMENT_TEMPLATES->value],
                [PermissionEnum::FORCE_DELETE_DOCUMENT_TEMPLATES->value],
                [PermissionEnum::IMPORT_DOCUMENT_TEMPLATES->value],
                [PermissionEnum::EXPORT_DOCUMENT_TEMPLATES->value],
                [PermissionEnum::CRUD_DOCUMENTS_SETTING_TEMPLATES->value],
                [PermissionEnum::VIEW_DOCUMENT_TEMPLATES_AUDIT_TRAIL->value],
                [PermissionEnum::VIEW_ANY_FEE_STRUCTURES->value],
                [PermissionEnum::VIEW_FEE_STRUCTURES->value],
                [PermissionEnum::CREATE_FEE_STRUCTURES->value],
                [PermissionEnum::UPDATE_FEE_STRUCTURES->value],
                [PermissionEnum::DELETE_FEE_STRUCTURES->value],
                [PermissionEnum::RESTORE_FEE_STRUCTURES->value],
                [PermissionEnum::FORCE_DELETE_FEE_STRUCTURES->value],
                [PermissionEnum::IMPORT_FEE_STRUCTURES->value],
                [PermissionEnum::EXPORT_FEE_STRUCTURES->value],
                [PermissionEnum::CRUD_FEE_STRUCTURES->value],
                [PermissionEnum::VIEW_FEE_STRUCTURES_AUDIT_TRAIL->value],
            ],
            'shared' => [
                [PermissionEnum::VIEW_ANY_BANK_DETAILS->value],
                [PermissionEnum::VIEW_BANK_DETAILS->value],
                [PermissionEnum::CREATE_BANK_DETAILS->value],
                [PermissionEnum::UPDATE_BANK_DETAILS->value],
                [PermissionEnum::DELETE_BANK_DETAILS->value],
                [PermissionEnum::RESTORE_BANK_DETAILS->value],
                [PermissionEnum::FORCE_DELETE_BANK_DETAILS->value],
                [PermissionEnum::IMPORT_BANK_DETAILS->value],
                [PermissionEnum::EXPORT_BANK_DETAILS->value],
                [PermissionEnum::VIEW_ANY_ADDRESSES->value],
                [PermissionEnum::VIEW_ADDRESSES->value],
                [PermissionEnum::CREATE_ADDRESSES->value],
                [PermissionEnum::UPDATE_ADDRESSES->value],
                [PermissionEnum::DELETE_ADDRESSES->value],
                [PermissionEnum::RESTORE_ADDRESSES->value],
                [PermissionEnum::FORCE_DELETE_ADDRESSES->value],
                [PermissionEnum::IMPORT_ADDRESSES->value],
                [PermissionEnum::EXPORT_ADDRESSES->value],
                [PermissionEnum::VIEW_ANY_CONTACTS->value],
                [PermissionEnum::VIEW_CONTACTS->value],
                [PermissionEnum::CREATE_CONTACTS->value],
                [PermissionEnum::UPDATE_CONTACTS->value],
                [PermissionEnum::DELETE_CONTACTS->value],
                [PermissionEnum::RESTORE_CONTACTS->value],
                [PermissionEnum::FORCE_DELETE_CONTACTS->value],
                [PermissionEnum::IMPORT_CONTACTS->value],
                [PermissionEnum::EXPORT_CONTACTS->value],
                [PermissionEnum::VIEW_ANY_NEXT_OF_KINS->value],
                [PermissionEnum::VIEW_NEXT_OF_KINS->value],
                [PermissionEnum::CREATE_NEXT_OF_KINS->value],
                [PermissionEnum::UPDATE_NEXT_OF_KINS->value],
                [PermissionEnum::DELETE_NEXT_OF_KINS->value],
                [PermissionEnum::RESTORE_NEXT_OF_KINS->value],
                [PermissionEnum::FORCE_DELETE_NEXT_OF_KINS->value],
                [PermissionEnum::IMPORT_NEXT_OF_KINS->value],
                [PermissionEnum::EXPORT_NEXT_OF_KINS->value],
            ],
            'students' => [
                [PermissionEnum::VIEW_OWN_STUDENT_DASHBOARD->value],
                [PermissionEnum::MANAGE_OWN_STUDENT_PERSONAL_DETAILS->value],
                [PermissionEnum::MANAGE_OWN_STUDENT_PROGRAM_DETAILS->value],
                [PermissionEnum::MANAGE_OWN_STUDENT_SPONSOR_DETAILS->value],
                [PermissionEnum::MANAGE_OWN_STUDENT_CONTACT_DETAILS->value],
                [PermissionEnum::MANAGE_OWN_STUDENT_FINANCIAL_DETAILS->value],
                [PermissionEnum::MANAGE_OWN_STUDENT_ACADEMIC_DETAILS->value],
                [PermissionEnum::MANAGE_STUDENTS_METADATA->value],
                [PermissionEnum::VIEW_ANY_STUDENTS->value],
                [PermissionEnum::VIEW_STUDENTS->value],
                [PermissionEnum::CREATE_STUDENTS->value],
                [PermissionEnum::UPDATE_STUDENTS->value],
                [PermissionEnum::DELETE_STUDENTS->value],
                [PermissionEnum::RESTORE_STUDENTS->value],
                [PermissionEnum::FORCE_DELETE_STUDENTS->value],
                [PermissionEnum::IMPORT_STUDENTS->value],
                [PermissionEnum::EXPORT_STUDENTS->value],
                [PermissionEnum::CRUD_STUDENTS_SETTINGS->value],
                [PermissionEnum::VIEW_STUDENTS_AUDIT_TRAIL->value],
            ],
            'enrolments' => [
                [PermissionEnum::VIEW_ANY_STUDENT_PROGRAMS->value],
                [PermissionEnum::VIEW_STUDENT_PROGRAMS->value],
                [PermissionEnum::CREATE_STUDENT_PROGRAMS->value],
                [PermissionEnum::UPDATE_STUDENT_PROGRAMS->value],
                [PermissionEnum::DELETE_STUDENT_PROGRAMS->value],
                [PermissionEnum::RESTORE_STUDENT_PROGRAMS->value],
                [PermissionEnum::FORCE_DELETE_STUDENT_PROGRAMS->value],
                [PermissionEnum::IMPORT_STUDENT_PROGRAMS->value],
                [PermissionEnum::EXPORT_STUDENT_PROGRAMS->value],
                [PermissionEnum::CRUD_STUDENT_PROGRAMS_SETTINGS->value],
                [PermissionEnum::VIEW_STUDENT_PROGRAMS_AUDIT_TRAIL->value],
                [PermissionEnum::VERIFY_CLASS_LIST->value],
                [PermissionEnum::CREATE_CLASS_LIST->value],
                [PermissionEnum::UPDATE_CLASS_LIST->value],
                [PermissionEnum::DELETE_CLASS_LIST->value],
                [PermissionEnum::VIEW_CLASS_LIST->value],
                [PermissionEnum::MANAGE_FINAL_CLASS_LIST->value],
            ],
            'examinations' => [
                [PermissionEnum::VIEW_ANY_EXAMINATION->value],
                [PermissionEnum::VIEW_EXAMINATION->value],
                [PermissionEnum::CREATE_EXAMINATION->value],
                [PermissionEnum::UPDATE_EXAMINATION->value],
                [PermissionEnum::DELETE_EXAMINATION->value],
                [PermissionEnum::RESTORE_EXAMINATION->value],
                [PermissionEnum::FORCE_DELETE_EXAMINATION->value],
                [PermissionEnum::IMPORT_EXAMINATION->value],
                [PermissionEnum::EXPORT_EXAMINATION->value],
                [PermissionEnum::CRUD_EXAMINATION_SETTINGS->value],
                [PermissionEnum::VIEW_EXAMINATION_AUDIT_TRAIL->value],
            ],
            'accommodations' => [
                [PermissionEnum::VIEW_ANY_ACCOMMODATIONS->value],
                [PermissionEnum::VIEW_ACCOMMODATIONS->value],
                [PermissionEnum::CREATE_ACCOMMODATIONS->value],
                [PermissionEnum::UPDATE_ACCOMMODATIONS->value],
                [PermissionEnum::DELETE_ACCOMMODATIONS->value],
                [PermissionEnum::RESTORE_ACCOMMODATIONS->value],
                [PermissionEnum::FORCE_DELETE_ACCOMMODATIONS->value],
                [PermissionEnum::IMPORT_ACCOMMODATIONS->value],
                [PermissionEnum::EXPORT_ACCOMMODATIONS->value],
                [PermissionEnum::CRUD_ACCOMMODATIONS_SETTINGS->value],
                [PermissionEnum::VIEW_ACCOMMODATIONS_AUDIT_TRAIL->value],
            ],
        ];
        foreach ($permissions as $key => $rows) {
            $module = Module::where('title', $key)->first();
            foreach ($rows as $row) {
                $exist = Permission::where('name', $row[0])->first();
                if (!$exist instanceof Permission) {
                    Permission::create(['name' => $row[0], 'module_id' => $module?->id]);
                }
            }
        }
    }
}
