import { IconName } from '@/enums/icons';
import {
    Angry as Empty,
    AppWindow as Generic,
    ArrowDown,
    ArrowLeft,
    ArrowRightFromLine as Export,
    ArrowRightToLine as Import,
    ArrowUp,
    Award,
    Bed,
    BookCheck,
    BookMarked,
    BriefcaseBusiness,
    Building2 as Company,
    Calendar,
    Check,
    CheckCheck as Done,
    CheckIcon,
    ChevronDown,
    ChevronLeft,
    ChevronRight,
    ChevronsLeft as ChevronDoubleLeft,
    ChevronsRight as ChevronDoubleRight,
    ChevronsUpDown,
    Circle,
    CircleAlert as Warning,
    CircleArrowDown as ArrowDownCircleOutline,
    CircleArrowUp as ArrowUpCircleOutline,
    CircleCheckBig as CheckBox,
    CircleDollarSign as Money,
    CircleDollarSignIcon,
    CircleUser as UserAvatar,
    ClipboardPlus as Report,
    Cog as Cogs,
    Contact,
    CornerDownLeft,
    CreditCard as Card,
    Dot,
    Ellipsis as DotsHorizontal,
    EllipsisVertical as DotsVertical,
    Eye,
    File,
    FileSearch,
    Fingerprint,
    Folder,
    FolderArchive as Archive,
    Gift,
    GitPullRequestArrow as Request,
    GraduationCap,
    History,
    Info,
    LayoutDashboard as Dashboard,
    List,
    ListFilter as Filter,
    LoaderCircle as Loader,
    LogOut as Logout,
    MailCheck as PersonChat,
    MapPinCheck as Location,
    MapPinHouse as Address,
    Megaphone,
    Menu,
    MoonStar as Dark,
    OctagonAlert as Danger,
    PackageSearch as Product,
    Pencil as Edit,
    Plus,
    Recycle,
    RefreshCcw as Refresh,
    Route,
    School,
    Search,
    Settings,
    Settings2 as Types,
    Shield,
    SquareArrowOutUpRight as OpenLink,
    Sun as Light,
    Trash2 as Trash,
    User as Scheme,
    UserCheck,
    UserPlus,
    Users,
    UserSearch,
    WalletCards,
    MonitorCheck,
    X as Close,
    ReceiptText, CircleX
} from 'lucide-vue-next';
import type { Component } from 'vue';

const icons: Record<IconName, Component> = {
    [IconName.add]: Plus,
    [IconName.angle_right]: ChevronRight,
    [IconName.back]: CornerDownLeft,
    [IconName.back_straight]: ArrowLeft,
    [IconName.card]: Card,
    [IconName.check]: Check,
    [IconName.circle]: Circle,
    [IconName.dot]: Dot,
    [IconName.check_box]: CheckBox,
    [IconName.check_done]: Done,
    [IconName.chevron_right]: ChevronRight,
    [IconName.chevron_down]: ChevronDown,
    [IconName.close]: Close,
    [IconName.cogs]: Cogs,
    [IconName.company]: Company,
    [IconName.dots_vertical]: DotsVertical,
    [IconName.dots_horizontal]: DotsHorizontal,
    [IconName.edit]: Edit,
    [IconName.empty]: Empty,
    [IconName.export]: Export,
    [IconName.file]: File,
    [IconName.filter]: Filter,
    [IconName.generic]: Generic,
    [IconName.import]: Import,
    [IconName.location]: Location,
    [IconName.menu]: Menu,
    [IconName.refresh]: Refresh,
    [IconName.scheme]: Scheme,
    [IconName.user]: UserAvatar,
    [IconName.chevron_left]: ChevronLeft,
    [IconName.chevron_double_left]: ChevronDoubleLeft,
    [IconName.chevron_double_right]: ChevronDoubleRight,
    [IconName.arrow_down_circle]: ArrowDownCircleOutline,
    [IconName.arrow_up_circle]: ArrowUpCircleOutline,
    [IconName.money]: Money,
    [IconName.dashboard]: Dashboard,
    [IconName.settings]: Settings,
    [IconName.users]: Users,
    [IconName.file_search]: FileSearch,
    [IconName.request]: Request,
    [IconName.report]: Report,
    [IconName.user_search]: UserSearch,
    [IconName.person_chat]: PersonChat,
    [IconName.trash]: Trash,
    [IconName.eye]: Eye,
    [IconName.logout]: Logout,
    [IconName.list]: List,
    [IconName.type]: Types,
    [IconName.product]: Product,
    [IconName.user_add]: UserPlus,
    [IconName.shield]: Shield,
    [IconName.archive]: Archive,
    [IconName.restore]: Recycle,
    [IconName.open_link]: OpenLink,
    [IconName.dark]: Dark,
    [IconName.light]: Light,
    [IconName.folder]: Folder,
    [IconName.chevrons_up_down]: ChevronsUpDown,
    [IconName.loader]: Loader,
    [IconName.info]: Info,
    [IconName.warning]: Warning,
    [IconName.danger]: Danger,
    [IconName.search]: Search,
    [IconName.check_icon]: CheckIcon,
    [IconName.bed]: Bed,
    [IconName.school]: School,
    [IconName.user_check]: UserCheck,
    [IconName.book_check]: BookCheck,
    [IconName.arrow_up]: ArrowUp,
    [IconName.arrow_down]: ArrowDown,
    [IconName.contact]: Contact,
    [IconName.address]: Address,
    [IconName.graduation_cape]: GraduationCap,
    [IconName.gift]: Gift,
    [IconName.dollar]: CircleDollarSignIcon,
    [IconName.award]: Award,
    [IconName.wallet_cards]: WalletCards,
    [IconName.briefcase]: BriefcaseBusiness,
    [IconName.history]: History,
    [IconName.finger_print]: Fingerprint,
    [IconName.calendar]: Calendar,
    [IconName.megaphone]: Megaphone,
    [IconName.bookmark]: BookMarked,
    [IconName.route]: Route,
    [IconName.monitor_check]: MonitorCheck,
    [IconName.receipt]: ReceiptText,
    [IconName.circle_x]: CircleX,
};

export { IconName, icons };
