import { IconName } from '@/enums/icons';
import {
    FolderArchive as Archive,
    CircleArrowDown as ArrowDownCircleOutline,
    ArrowLeft,
    CircleArrowUp as ArrowUpCircleOutline,
    Bed,
    CreditCard as Card,
    Check,
    CircleCheckBig as CheckBox,
    CheckIcon,
    ChevronsLeft as ChevronDoubleLeft,
    ChevronsRight as ChevronDoubleRight,
    ChevronDown,
    ChevronLeft,
    ChevronRight,
    ChevronsUpDown,
    Circle,
    X as Close,
    Cog as Cogs,
    Building2 as Company,
    CornerDownLeft,
    OctagonAlert as Danger,
    MoonStar as Dark,
    LayoutDashboard as Dashboard,
    CheckCheck as Done,
    Dot,
    Ellipsis as DotsHorizontal,
    EllipsisVertical as DotsVertical,
    Pencil as Edit,
    Angry as Empty,
    ArrowRightFromLine as Export,
    Eye,
    File,
    FileSearch,
    ListFilter as Filter,
    Folder,
    AppWindow as Generic,
    ArrowRightToLine as Import,
    Info,
    Sun as Light,
    List,
    LoaderCircle as Loader,
    MapPinCheck as Location,
    LogOut as Logout,
    Menu,
    CircleDollarSign as Money,
    SquareArrowOutUpRight as OpenLink,
    MailCheck as PersonChat,
    Plus,
    PackageSearch as Product,
    Recycle,
    RefreshCcw as Refresh,
    ClipboardPlus as Report,
    GitPullRequestArrow as Request,
    User as Scheme,
    School,
    Search,
    Settings,
    Fingerprint as Shield,
    Trash2 as Trash,
    Settings2 as Types,
    CircleUser as UserAvatar,
    UserCheck,
    UserPlus,
    Users,
    UserSearch,
    CircleAlert as Warning, BookCheck
} from 'lucide-vue-next';
import type { Component } from 'vue';

const icons: Record<IconName, Component> = {
    [IconName.add]: Plus,
    [IconName.angle_right]: ChevronRight,
    [IconName.back]: CornerDownLeft,
    [IconName.back_straight]: ArrowLeft,
    [IconName.card]: Card,
    [IconName.check]: Check,
    [IconName.circle]: Circle,
    [IconName.dot]: Dot,
    [IconName.check_box]: CheckBox,
    [IconName.check_done]: Done,
    [IconName.chevron_right]: ChevronRight,
    [IconName.chevron_down]: ChevronDown,
    [IconName.close]: Close,
    [IconName.cogs]: Cogs,
    [IconName.company]: Company,
    [IconName.dots_vertical]: DotsVertical,
    [IconName.dots_horizontal]: DotsHorizontal,
    [IconName.edit]: Edit,
    [IconName.empty]: Empty,
    [IconName.export]: Export,
    [IconName.file]: File,
    [IconName.filter]: Filter,
    [IconName.generic]: Generic,
    [IconName.import]: Import,
    [IconName.location]: Location,
    [IconName.menu]: Menu,
    [IconName.refresh]: Refresh,
    [IconName.scheme]: Scheme,
    [IconName.user]: UserAvatar,
    [IconName.chevron_left]: ChevronLeft,
    [IconName.chevron_double_left]: ChevronDoubleLeft,
    [IconName.chevron_double_right]: ChevronDoubleRight,
    [IconName.arrow_down_circle]: ArrowDownCircleOutline,
    [IconName.arrow_up_circle]: ArrowUpCircleOutline,
    [IconName.money]: Money,
    [IconName.dashboard]: Dashboard,
    [IconName.settings]: Settings,
    [IconName.users]: Users,
    [IconName.file_search]: FileSearch,
    [IconName.request]: Request,
    [IconName.report]: Report,
    [IconName.user_search]: UserSearch,
    [IconName.person_chat]: PersonChat,
    [IconName.trash]: Trash,
    [IconName.eye]: Eye,
    [IconName.logout]: Logout,
    [IconName.list]: List,
    [IconName.type]: Types,
    [IconName.product]: Product,
    [IconName.user_add]: UserPlus,
    [IconName.shield]: Shield,
    [IconName.archive]: Archive,
    [IconName.restore]: Recycle,
    [IconName.open_link]: OpenLink,
    [IconName.dark]: Dark,
    [IconName.light]: Light,
    [IconName.folder]: Folder,
    [IconName.chevrons_up_down]: ChevronsUpDown,
    [IconName.loader]: Loader,
    [IconName.info]: Info,
    [IconName.warning]: Warning,
    [IconName.danger]: Danger,
    [IconName.search]: Search,
    [IconName.check_icon]: CheckIcon,
    [IconName.bed]: Bed,
    [IconName.school]: School,
    [IconName.user_check]: UserCheck,
    [IconName.book_check]: BookCheck,
};

export { IconName, icons };
