import type { Component } from 'vue';
import {
	Plus,
	ChevronRight,
	CornerDownLeft,
	ArrowLeft,
	MapPinCheck as Location,
	CircleDollarSign as Money,
	X as Close,
	LayoutDashboard as Dashboard,
	Menu,
	Recycle,
	Settings,
	Check, Dot, Circle,
	EllipsisVertical as DotsVertical,
	Ellipsis as DotsHorizontal,
	FileSearch,
	GitPullRequestArrow as Request,
	ListFilter as Filter,
	MoonStar as Dark,
	RefreshCcw as Refresh,
	ClipboardPlus as Report,
	UserSearch,
	File,
	UserPlus,
	Users,
	Eye,
	Cog as Cogs,
	User as Scheme,
	Building2 as Company,
	Settings2 as Types,
	CircleUser as UserAvatar,
	AppWindow as Generic,
	List,
	ArrowRightFromLine as Export,
	ArrowRightToLine as Import,
	CircleCheckBig as CheckBox,
	ChevronsLeft as ChevronDoubleLeft,
	ChevronsRight as ChevronDoubleRight,
	ChevronDown,
	ChevronLeft,
	FolderArchive as Archive,
	Pencil as Edit,
	Folder,
	SquareArrowOutUpRight as OpenLink,
	MailCheck as PersonChat,
	PackageSearch as Product,
	Fingerprint as Shield,
	Sun as Light,
	CircleArrowDown as ArrowDownCircleOutline,
	CircleArrowUp as ArrowUpCircleOutline,
	CreditCard as Card,
	CheckCheck as Done,
	LogOut as Logout,
	Trash2 as Trash,
	Angry as Empty,
	ChevronsUpDown,
	CheckIcon,
	LoaderCircle as Loader,
	Info,
	CircleAlert as Warning,
	OctagonAlert as Danger,
	Search, Bed
} from 'lucide-vue-next';
import { IconName } from '@/enums/icons';
const icons: Record<IconName, Component> = {
	[IconName.add]: Plus,
	[IconName.angle_right]: ChevronRight,
	[IconName.back]: CornerDownLeft,
	[IconName.back_straight]: ArrowLeft,
	[IconName.card]: Card,
	[IconName.check]: Check,
	[IconName.circle]: Circle,
	[IconName.dot]: Dot,
	[IconName.check_box]: CheckBox,
	[IconName.check_done]: Done,
	[IconName.chevron_right]: ChevronRight,
	[IconName.chevron_down]: ChevronDown,
	[IconName.close]: Close,
	[IconName.cogs]: Cogs,
	[IconName.company]: Company,
	[IconName.dots_vertical]: DotsVertical,
	[IconName.dots_horizontal]: DotsHorizontal,
	[IconName.edit]: Edit,
	[IconName.empty]: Empty,
	[IconName.export]: Export,
	[IconName.file]: File,
	[IconName.filter]: Filter,
	[IconName.generic]: Generic,
	[IconName.import]: Import,
	[IconName.location]: Location,
	[IconName.menu]: Menu,
	[IconName.refresh]: Refresh,
	[IconName.scheme]: Scheme,
	[IconName.user]: UserAvatar,
	[IconName.chevron_left]: ChevronLeft,
	[IconName.chevron_double_left]: ChevronDoubleLeft,
	[IconName.chevron_double_right]: ChevronDoubleRight,
	[IconName.arrow_down_circle]: ArrowDownCircleOutline,
	[IconName.arrow_up_circle]: ArrowUpCircleOutline,
	[IconName.money]: Money,
	[IconName.dashboard]: Dashboard,
	[IconName.settings]: Settings,
	[IconName.users]: Users,
	[IconName.file_search]: FileSearch,
	[IconName.request]: Request,
	[IconName.report]: Report,
	[IconName.user_search]: UserSearch,
	[IconName.person_chat]: PersonChat,
	[IconName.trash]: Trash,
	[IconName.eye]: Eye,
	[IconName.logout]: Logout,
	[IconName.list]: List,
	[IconName.type]: Types,
	[IconName.product]: Product,
	[IconName.user_add]: UserPlus,
	[IconName.shield]: Shield,
	[IconName.archive]: Archive,
	[IconName.restore]: Recycle,
	[IconName.open_link]: OpenLink,
	[IconName.dark]: Dark,
	[IconName.light]: Light,
	[IconName.folder]: Folder,
	[IconName.chevrons_up_down]: ChevronsUpDown,
	[IconName.loader]: Loader,
	[IconName.info]: Info,
	[IconName.warning]: Warning,
	[IconName.danger]: Danger,
	[IconName.search]: Search,
	[IconName.check_icon]: CheckIcon,
	[IconName.bed]: Bed,
};


export {
	icons, IconName
};
